### ISSUE TITLE
AWS OpsWorks Builds failing

### ISSUE THREAD

**Issue by krsoundtek** [escapestudios-cookbooks/newrelic#234]
AWS OpsWorks Builds started failing yesterday when using this repository even with just the default server monitoring.   Error below. 

================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb
================================================================================
 
 
NoMethodError
-------------
undefined method `provides' for #<Class:0x0056382bb321f8>
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb:22:in `class_from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb:
 
15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
16:  # See the License for the specific language governing permissions and
17:  # limitations under the License.
18:  #
19:  
20:  use_inline_resources
21:  
22>> provides :msys_archive
23:  
24:  action :unpack do
25:    directory msys_dir do
26:      action :create
27:    end
28:  
29:    directory "dir-#{mingw_dir}" do
30:      action :create
31:      path mingw_dir
 
 
 
[2016-02-17T23:24:07+00:00] ERROR: Running exception handlers
[2016-02-17T23:24:07+00:00] ERROR: Exception handlers complete
[2016-02-17T23:24:07+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2016-02-17T23:24:07+00:00] ERROR: undefined method `provides' for #<Class:0x0056382bb321f8>
[2016-02-17T23:24:07+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by djoos** [comment]
Hi @krsoundtek,

the error you are getting is caused by the build-essentials cookbook. The 'provides' syntax on resources is supported in Chef 11, however on providers (as per the stack trace) only in Chef 12...

I'd suggest you pin to an older version of the build-essentials cookbook to get round the issue.

Hope this helps!

Kind regards,
David

**Comment by krsoundtek** [comment]
The only Cookbook that we are calling is newrelic and we have a version limit setup for the current version released in January.  I would think that this would need to be changed in the new relic repo to limit the version on its dependency.   The issue is that AWS only supports Chef 12 for Windows.  So right now any linux stacks must use 11.

**Comment by djoos** [comment]
Hi @krsoundtek,

thanks for your feedback! The newrelic-cookbook depends on the python-cookbook, which in it's turn has a dependency on the build-essential cookbook. I understand you locked the newrelic-cookbook version, however without locking the related cookbooks, you'll get the latest of each respectively, which is the root cause of the issue you are experiencing with the build-essentials cookbook...

Hope this helps!

Kind regards,
David

**Comment by djoos** [comment]
...actually by the looks of it Chef 11 compatibility seems to have been addressed today in 2.3.1 of build-essential - that will probably address the issue you are experiencing as well!

Please let me know how you get on...

Thanks in advance!

**Comment by krsoundtek** [comment]
That did resolve the issue.  Thank you very much for taking the time and letting me know about the update.

**Comment by djoos** [comment]
Great stuff, you're welcome!

Tip: try to lock down all versions of all cookbooks (get a list of them via running 'berks list' when using berkshelf), it'll save you a lot of headache along the way!

Kind regards,
David
